# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Class_list')),
            ],
        ),
    ]
